/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface ExtendedUserProfile {
  'userRole' : UserRole,
  'principal' : Principal,
  'displayName' : string,
  'roleLabel' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'company' : string,
  'message' : string,
  'isVisible' : boolean,
  'rating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<
    [string, string, string, bigint, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolioItem' : ActorMethod<[string, string, string, string], bigint>,
  'createUserProfile' : ActorMethod<[string, string], undefined>,
  'deleteContactMessage' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllUserProfiles' : ActorMethod<[], Array<ExtendedUserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ExtendedUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [ExtendedUserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'getVisibleTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modifyTestimonialVisibility' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];